USE DATABASE SNOWFLAKE_SAMPLE_DATA;
DESC TABLE TPCDS_SF100TCL.STORE_SALES;

SELECT COUNT(*) FROM TPCDS_SF100TCL.STORE_SALES;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE;

CREATE OR REPLACE TABLE BRONZE.STORE_SALES AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 5000000000;

SELECT COUNT(*) FROM BRONZE.STORE_SALES;

SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

DESC TABLE BRONZE.STORE_SALES;

SELECT COUNT(*) AS TOTAL_ROWS,
    COUNT(ss_sales_price) as non_null_sales_price
FROM BRONZE.STORE_SALES;

select min(ss_sold_date_sk),max(ss_sold_date_sk)
from BRONZE.STORE_SALES;