USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE OR REPLACE TABLE GOLD.SALES_BY_STATE AS
SELECT 
    D.STATE,
    SUM(F.SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES F
JOIN SILVER.CUSTOMER_DIM D
ON F.CUSTOMER_SK = D.CUSTOMER_SK
GROUP BY D.STATE;

CREATE OR REPLACE TABLE GOLD.SALES_BY_YEAR AS
SELECT 
    YEAR(TRANSACTION_DATE) AS SALES_YEAR,
    SUM(SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES 
GROUP BY SALES_YEAR;

SELECT * FROM GOLD.SALES_BY_STATE;
SELECT * FROM GOLD.SALES_BY_YEAR;

-- SALES BY STORE EVERY MONTH
CREATE OR REPLACE TABLE GOLD.MONTHLY_SALES AS
SELECT
    DATE_TRUNC('month', transaction_date) AS sales_month ,
    SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY sales_month;

SELECT * FROM GOLD.MONTHLY_SALES;

-- TOP 10 STORES BY SALES
CREATE OR REPLACE TABLE GOLD.TOP_STORES AS
SELECT
    store_id,
    SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY store_id
ORDER BY total_sales DESC
LIMIT 10;

SELECT * FROM GOLD.TOP_STORES;

-- performance validation
SELECT SUM(SALES_PRICE) FROM SILVER.FACT_SALES;
SELECT SUM(TOTAL_SALES) FROM GOLD.SALES_BY_STATE;
