DESC TABLE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER;
DESC TABLE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE OR REPLACE TABLE SILVER.CUSTOMER_DIM(
    CUSTOMER_SK NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    STATE STRING,
    START_DATE DATE,
    END_DATE DATE,
    IS_CURRENT STRING
);

--INTIAL LOAD

INSERT INTO SILVER.CUSTOMER_DIM (CUSTOMER_ID, STATE, START_DATE, END_DATE, IS_CURRENT)
SELECT C.C_CUSTOMER_SK, CA.CA_STATE, CURRENT_DATE(), NULL, 'Y'
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS CA
ON C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK;

SELECT COUNT(*) FROM SILVER.CUSTOMER_DIM;
SELECT * FROM SILVER.CUSTOMER_DIM LIMIT 5;

--CREATE A SMALL STAGE
CREATE OR REPLACE TABLE SILVER.CUSTOMER_STAGE AS 
SELECT CUSTOMER_ID, STATE FROM SILVER.CUSTOMER_DIM
WHERE IS_CURRENT = 'Y';

-- MAUALLY UPDATE ONE ROW
UPDATE SILVER.CUSTOMER_STAGE
SET STATE = 'TX'
WHERE CUSTOMER_ID = 71049106;

SELECT * FROM SILVER.CUSTOMER_STAGE
WHERE CUSTOMER_ID = 71049106;

-- IMPLEMENT STAGE 2 USING MERGE
MERGE INTO SILVER.CUSTOMER_DIM TARGET 
USING SILVER.CUSTOMER_STAGE SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
AND TARGET.IS_CURRENT = 'Y'
WHEN MATCHED AND TARGET.STATE <> SOURCE.STATE THEN 
    UPDATE SET END_DATE = CURRENT_DATE, IS_CURRENT = 'N'
WHEN NOT MATCHED THEN 
    INSERT (CUSTOMER_ID, STATE, START_DATE, END_DATE, IS_CURRENT)
    VALUES (SOURCE.CUSTOMER_ID, SOURCE.STATE, CURRENT_DATE, NULL, 'Y');

-- VALIDATE SCD BEHAVIOR
SELECT * FROM SILVER.CUSTOMER_DIM
WHERE CUSTOMER_ID = 71049106;